version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./apps/backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./apps/backend
    restart: on-failure
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./apps/frontend
    restart: on-failure
    env_file:
      - ./apps/frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
