# Stage 1: build
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: produção
FROM node:18-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Copia node_modules do builder
COPY --from=builder /app/node_modules ./node_modules

# Copia build e arquivos necessários para rodar Next.js
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]
