name: CI - Backend & Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend Build, Test and Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd apps/backend
          npm install

      - name: Run backend tests
        run: |
          cd apps/backend
          npm test

      - name: Build backend
        run: |
          cd apps/backend
          npm run build

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh
          export PATH=$HOME/.railway/bin:$PATH
          railway --version

      - name: Deploy backend to Railway
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
        run: |
          export PATH=$HOME/.railway/bin:$PATH
          cd apps/backend
          railway up --detach

  frontend:
    name: Frontend Build, Test and Deploy to Vercel
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd apps/frontend
          npm install

      - name: Run frontend tests
        run: |
          cd apps/frontend
          npm test

      - name: Build frontend
        run: |
          cd apps/frontend
          npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy frontend to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd apps/frontend
          vercel --prod --token $VERCEL_TOKEN
